# Generated by Django 5.1.4 on 2024-12-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountStatus",
            fields=[
                ("acc_status_id", models.AutoField(primary_key=True, serialize=False)),
                ("acc_status_name", models.CharField(max_length=50, unique=True)),
            ],
            options={"db_table": "account_status", "managed": False,},
        ),
        migrations.CreateModel(
            name="Addresss",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                ("house_num", models.CharField(blank=True, max_length=20, null=True)),
                ("street", models.CharField(blank=True, max_length=150, null=True)),
                ("purok_sitio", models.CharField(blank=True, max_length=50, null=True)),
                ("barangay", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={"db_table": "addresss", "managed": False,},
        ),
        migrations.CreateModel(
            name="BlotterCase",
            fields=[
                (
                    "blotter_case_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("blotter_case_num", models.CharField(max_length=15)),
                ("blotter_case_name", models.TextField()),
                ("date_filed", models.DateField()),
                ("date_settled", models.DateField(blank=True, null=True)),
                ("time_settled", models.TimeField(blank=True, null=True)),
                ("date_added", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "blotter_case", "managed": False,},
        ),
        migrations.CreateModel(
            name="BlotterLog",
            fields=[
                ("blotter_log_id", models.AutoField(primary_key=True, serialize=False)),
                ("blotter_case_num", models.CharField(max_length=15)),
                ("blotter_case_name", models.CharField(max_length=150)),
                ("form_type", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={"db_table": "blotter_log", "managed": False,},
        ),
        migrations.CreateModel(
            name="BlotterStatus",
            fields=[
                (
                    "blotter_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("blotter_status_name", models.CharField(max_length=50)),
            ],
            options={"db_table": "blotter_status", "managed": False,},
        ),
        migrations.CreateModel(
            name="Casee",
            fields=[
                ("case_id", models.AutoField(primary_key=True, serialize=False)),
                ("case_name", models.CharField(max_length=255)),
            ],
            options={"db_table": "casee", "managed": False,},
        ),
        migrations.CreateModel(
            name="CaseType",
            fields=[
                ("case_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("case_type_name", models.CharField(max_length=50)),
            ],
            options={"db_table": "case_type", "managed": False,},
        ),
        migrations.CreateModel(
            name="CivilStatus",
            fields=[
                (
                    "civil_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("civil_status_name", models.CharField(max_length=20, unique=True)),
            ],
            options={"db_table": "civil_status", "managed": False,},
        ),
        migrations.CreateModel(
            name="CommonLog",
            fields=[
                ("common_log_id", models.AutoField(primary_key=True, serialize=False)),
                ("record_affected_id", models.IntegerField()),
                ("details", models.TextField()),
                ("date_time", models.DateTimeField()),
                ("table_affected", models.CharField(max_length=100)),
                ("actionn", models.CharField(max_length=50)),
            ],
            options={"db_table": "common_log", "managed": False,},
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                ("credentials_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("passwordd", models.CharField()),
            ],
            options={"db_table": "credential", "managed": False,},
        ),
        migrations.CreateModel(
            name="EducationalAttainment",
            fields=[
                ("education_id", models.AutoField(primary_key=True, serialize=False)),
                ("educ_level", models.CharField(max_length=150, unique=True)),
            ],
            options={"db_table": "educational_attainment", "managed": False,},
        ),
        migrations.CreateModel(
            name="FormDocumentation",
            fields=[
                (
                    "form_documentation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("form_image_data", models.BinaryField(blank=True, null=True)),
                ("upload_date", models.DateField()),
            ],
            options={"db_table": "form_documentation", "managed": False,},
        ),
        migrations.CreateModel(
            name="FormType",
            fields=[
                ("form_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("form_type_num", models.CharField(max_length=150)),
                ("form_type_name", models.TextField()),
            ],
            options={"db_table": "form_type", "managed": False,},
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                ("login_log_id", models.AutoField(primary_key=True, serialize=False)),
                ("login_time", models.DateTimeField()),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "login_log", "managed": False,},
        ),
        migrations.CreateModel(
            name="LogSubsystem",
            fields=[
                (
                    "log_subsystem_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("log_subsystem_name", models.CharField(max_length=100)),
            ],
            options={"db_table": "log_subsystem", "managed": False,},
        ),
        migrations.CreateModel(
            name="NonResident",
            fields=[
                (
                    "non_resident_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("contact_num", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={"db_table": "non_resident", "managed": False,},
        ),
        migrations.CreateModel(
            name="Quarter",
            fields=[
                ("quarter_id", models.AutoField(primary_key=True, serialize=False)),
                ("quarterr", models.CharField(max_length=50, unique=True)),
            ],
            options={"db_table": "quarter", "managed": False,},
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                ("religion_id", models.AutoField(primary_key=True, serialize=False)),
                ("religion_name", models.CharField(max_length=100, unique=True)),
            ],
            options={"db_table": "religion", "managed": False,},
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                ("resident_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField()),
                ("first_name", models.CharField()),
                ("middle_name", models.CharField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, max_length=1, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("is_voter", models.BooleanField(blank=True, null=True)),
            ],
            options={"db_table": "resident", "managed": False,},
        ),
        migrations.CreateModel(
            name="ResidentCategory",
            fields=[
                (
                    "resident_category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "resident_category_legend",
                    models.CharField(max_length=50, unique=True),
                ),
                ("resident_category_description", models.CharField(max_length=50)),
            ],
            options={"db_table": "resident_category", "managed": False,},
        ),
        migrations.CreateModel(
            name="ResidentHistory",
            fields=[
                (
                    "resident_history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("sex", models.CharField(blank=True, max_length=1, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("date_transferred", models.DateField()),
                ("is_voter", models.BooleanField(blank=True, null=True)),
            ],
            options={"db_table": "resident_history", "managed": False,},
        ),
        migrations.CreateModel(
            name="ResidentStatus",
            fields=[
                (
                    "resident_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("resident_status_name", models.CharField(max_length=50, unique=True)),
            ],
            options={"db_table": "resident_status", "managed": False,},
        ),
        migrations.CreateModel(
            name="Rolee",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=50, unique=True)),
            ],
            options={"db_table": "rolee", "managed": False,},
        ),
        migrations.CreateModel(
            name="Userr",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={"db_table": "userr", "managed": False,},
        ),
        migrations.CreateModel(
            name="VoterRecord",
            fields=[
                (
                    "voter_record_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("precinct_num", models.CharField(max_length=10)),
                ("date_added", models.DateField(blank=True, null=True)),
            ],
            options={"db_table": "voter_record", "managed": False,},
        ),
    ]
