name: Integration

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.4, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput

    - name: Add Environment Variables
      run: |
        export DB_NAME=${{ env.DB_NAME }} && \
        export DB_ENGINE=${{ env.DB_ENGINE }} && \
        export DB_SECRET_KEY=${{ env.DB_SECRET_KEY }} && \
        export DB_PORT=${{ env.DB_PORT }} && \
        export DB_USER=${{ env.DB_USER }} && \
        export DB_HOST=${{ env.DB_HOST }}

    - name: Integrate legacy DB
      run: python manage.py inspectdb | tee models.py

    - name: Check for Syntax Errors
      run: |
        find . -name "*.py" -exec python -m py_compile {} \;

    - name: Run Tests
      run: |
        python manage.py test
