name: Integration

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_ENGINE: ${{ vars.DB_ENGINE }}
      DB_SECRET_KEY: ${{ vars.DB_SECRET_KEY }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USER: ${{ vars.DB_USER }}
      DB_HOST: ${{ vars.DB_HOST }}

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.4, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput

    - name: Integrate legacy DB
      run: python manage.py inspectdb | tee models.py

    - name: Check for Syntax Errors
      run: |
        find . -name "*.py" -exec python -m py_compile {} \;

    - name: Run Tests
      run: |
        python manage.py test
